-- 코드를 작성해주세요
SELECT ID, CASE WHEN SIZE_PERCENT <= 0.25 THEN 'CRITICAL'
                WHEN SIZE_PERCENT <= 0.50 THEN 'HIGH'
                WHEN SIZE_PERCENT <= 0.75 THEN 'MEDIUM'
                ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, SIZE_OF_COLONY, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_PERCENT
      FROM ECOLI_DATA) AS T
ORDER BY ID ASC;

