-- 코드를 입력하세요
SELECT 
    IC.FLAVOR
FROM 
    FIRST_HALF FI
JOIN
    ICECREAM_INFO IC
ON
    FI.FLAVOR = IC.FLAVOR
WHERE
    FI.TOTAL_ORDER > 3000 AND
    IC.INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    TOTAL_ORDER DESC;